#!/bin/bash

set -e

GIT_PACKAGE_VERSION="2.18.0-r0"
OPENSSH_VERSION="7.7_p1-r2"
IMAGE_VERSION="2.18.0"

./build.sh ${GIT_PACKAGE_VERSION} ${OPENSSH_VERSION} ${IMAGE_VERSION}
./push.sh ${IMAGE_VERSION}