#!/bin/bash

set -e

GIT_PACKAGE_VERSION="2.15.0-r1"
OPENSSH_VERSION="7.5_p1-r8"
IMAGE_VERSION="2.15.0"

./build.sh ${GIT_PACKAGE_VERSION} ${OPENSSH_VERSION} ${IMAGE_VERSION}
./push.sh ${IMAGE_VERSION}