#!/bin/bash

set -e

GIT_PACKAGE_VERSION="2.26.2-r0"
OPENSSH_VERSION="8.3_p1-r0"
IMAGE_VERSION="2.26.0"

./build.sh ${GIT_PACKAGE_VERSION} ${OPENSSH_VERSION} ${IMAGE_VERSION}
./push.sh ${IMAGE_VERSION}