FROM alpine:edge

MAINTAINER Cape Codes <info@cape.codes>

ARG GIT_PACKAGE_VERSION=2.29.2-r0
ARG OPENSSH_PACKAGE_VERSION=8.4_p1-r1

RUN apk --update add bash expect git=${GIT_PACKAGE_VERSION} openssh-client=${OPENSSH_PACKAGE_VERSION} && \
    rm -rf /var/cache/apk/*

USER root
WORKDIR /root

RUN mkdir -p /.ssh

ENV HOME=/root
ENV UID=0
ENV GID=0
